version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - run: apt-get update && apt-get -qq -y install awscli
      - checkout
      - restore_cache:
          keys:
            - stack-{{ checksum "site.hs" }}-{{ checksum "eanalytica-www.cabal" }}-{{ checksum "stack.yaml" }}
            - stack
      - run: stack setup
      - run: stack install
      - save_cache:
          key: stack-{{ checksum "site.hs" }}-{{ checksum "eanalytica-www.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - .stack-work
            - ~/.stack
            - ~/.local/bin
      - restore_cache:
          key: sitecache-{{ checksum "site.hs" }}
      - run: ~/.local/bin/eanalytica-www build
      - save_cache:
          key: sitecache-{{ checksum "site.hs" }}-{{ epoch }}
          paths: _site
      - run: aws s3 sync _site s3://com.eanalytica.www2/
