version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache:
          keys: stack
      - run: stack setup
      - run: stack install
      - save_cache:
          key: stack
          paths:
            - .stack-work
            - ~/.stack
      - restore_cache:
          keys: site
      - run: ~/.local/bin/eanalytica-www build
      - save_cache:
          key: site
          paths: _site
