version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache:
          keys: stack
      - run: stack setup
      - run: stack build
      - save_cache:
          key: stack
          paths:
            - .stack-work
            - ~/.stack
