version: 2
jobs:
  build:
    docker:
      - image: eanalytica/www-build
    steps:
      - checkout
      - run: stack install -j1 --fast
      - restore_cache:
          key: sitecache-{{ checksum "site.hs" }}
      - run: ~/.local/bin/eanalytica-www build
      - save_cache:
          key: sitecache-{{ checksum "site.hs" }}-{{ epoch }}
          paths: _site
      - run: aws s3 sync _site s3://com.eanalytica.www2/
