---
title: Links from February
---
Here are some of the links I saved during February. This month I've selected
links around the theme of sport.

*** [[https://www.bbc.co.uk/sport/athletics/51387604][Sophie McKinna's £15,000 funding gamble]]
I've always been a sucker for a sporting underdog story and I really hope this
one has the Hollywood ending I've been led to expect.

Sophie McKinna (a British shotputter) turned down lottery funding and support
from UK Athletics and instead continues to work in her main career as a prison
officer whilst also being supported by local sponsors in Norfolk.

Since taking this path she has improved her personal bests and qualified for the
Tokyo Olympics. I find an athlete going out on their own and trying to thrive outside
the system inspirational in so many ways.

*** [[https://www.bbc.co.uk/sport/amp/rugby-union/51393335][Ice cream vans & Finn and Gregor's domestic]]
Scottish rugby player Gordon Reid describes his feelings during the 2019
Calcutta Cup match against England which Scotland /nearly/ won with a tremendous
second half comeback.

My Dad loves rugby and is a big Scotland fan so I take a mild interest and want
to see the team do well. And (again) who can resist an underdog story where a
nation of 5 million people (smaller than London!) takes on the biggest rugby
nation in the world in one of the oldest international sporting fixtures.

#+BEGIN_QUOTE
It's just total focus, we know we're on the cusp of doing
something special but it's just a matter of 'we just need to keep going'. We
know how good a team England are, we know they do come back so we need to keep
our foot on the throat.
#+END_QUOTE

*** [[https://boardgamegeek.com/thread/442795/chess-interesting-concept-ruined-too-many-design-f][Chess: An interesting concept ruined by too many design flaws]]
A humorous review of chess as if it were a modern board game.

#+BEGIN_QUOTE
The lightweight cardboard box contains hollow plastic pieces and a flimsy
cardboard map. The map is a collection of provinces represented by black and
white squares. The publisher should have considered adding some color to the
board, and maybe even some little drawings of castles, a la Carcassonne. This
would have suited the medieval theme very well.
#+END_QUOTE

#+BEGIN_QUOTE
Overall, I found Chess to be rather dull, with too much downtime and too little
to do. It has some interesting parts, but the numerous flaws discussed in this
review tend to bring the game down. It's also too simple and could have
benefited from some additional mechanics. The rules of Chess are so easy that
even hand held computers can be programmed to play the game well.
#+END_QUOTE

Makes you think about what actually makes a good game...

*** [[https://thegrowtheq.com/the-secret-to-resilience-a-good-story/][The Secret to Resilience? A Good Story]]
It is a truism that there are so many things we can't control but one of the
things we can always control is our reaction to events.

I find this easier said than done.

Steve Magness writes that if you have a (semi-) consistent internal narrative
about what type of person you are then it is easier to have positive reactions
to external events.

#+BEGIN_QUOTE
 When I fractured my femur [...] I did everything I could to stay positive. Sure, it sucked,
 especially because of the timing, and I let myself be sad. [...] I ran on that
 thing for like six weeks — it proved to me that I’m a pretty tough gal. I could
 challenge that toughness in bouncing back
#+END_QUOTE
